---
title: "Init_EDA"
author: "Connor Mignone"
date: "11/3/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
```

```{r}
atbats <- read_csv('ds_case_2/2019_atbats.csv')
pitching <- read_csv('ds_case_2/2019_pitches.csv')
```

Showing the difference in data using oversampling techniques
```{}
ggplot_ovs <- data_oversampling
ggplot_ovs$y_bin <- case_when(ggplot_ovs$y_bin == 1 ~ "Admit Patient", ggplot_ovs$y_bin == 0 ~ "Discharge Patient")

ggplot_os <- data_original_sampling
ggplot_os$y_bin <- case_when(ggplot_os$y_bin == 1 ~ "Admit Patient", ggplot_os$y_bin == 0 ~ "Discharge Patient")
ggplot(data = ggplot_os)+
  geom_bar(aes(as.factor(y_bin)))+
  labs(title = "Original Sampling Data", x = "Doctor Decision")+
  theme_classic()

ggplot(data = ggplot_ovs)+
  geom_bar(aes(as.factor(y_bin)))+
  labs(title = "Oversampled Data", x = "Doctor Decision")+
  theme_classic()
```
```{}
sum(data_original_sampling$y_bin == 1) / nrow(data_original_sampling)
```


```{r}
ggplot(data = atbats)+
    geom_bar(aes(x=event))+
 # facet_wrap(vars(p_throws))+
  labs(x = "Play Event")+
  theme_bw()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
ggplot(data = atbats)+
    geom_bar(aes(x=event))+
  facet_wrap(vars(p_throws))+
  labs(x = "Play Event")+
  theme_bw()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 5))
```


```{r}
ggplot(data = atbats)+
    geom_bar(aes(x=p_throws))+
  labs(x = "Throwing Hand")+
  theme_bw()
```

```{r}
ggplot(data = atbats)+
    geom_bar(aes(x=stand))+
  labs(x = "Batting Stance")+
  theme_bw()
```

```{r}
ggplot(data = pitching)+
    geom_histogram(aes(start_speed), bins = 20)+
#  facet_wrap(vars(y_bin))+
  labs(title = "Pitch Start Speed")
```

```{r}
ggplot(data = pitching)+
    geom_histogram(aes(end_speed), bins = 20)+
#  facet_wrap(vars(y_bin))+
  labs(title = "Pitch End Speed")
```

```{r}
ggplot(data = pitching)+
    geom_bar(aes(pitch_type))+
#  facet_wrap(vars(y_bin))+
  labs(title = "Pitch Type")
```
```{r}
ggplot(data = pitching)+
    geom_bar(aes(pitch_type))+
  facet_wrap(vars(s_count))+
  labs(title = "Pitch End Speed")
```